name: Docker Build and Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]

env:
  ECR_REPOSITORY: "demo-repository"
  EB_ENVIRONMENT: "MinimalApi-env"
  EB_APPLICATION: "MinimalApi"
  S3_BUCKET: "elasticbeanstalk-eu-central-1-785428641476"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build and push the Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
      run: |
        cd SimpleMinimalApi
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.run_id }} .
        echo "Pushing image to ECR..." $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.run_id }}
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.run_id }}
        echo ::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Zip Dockerrun.aws.json and upload to S3 bucket
      run: |
        cd SimpleMinimalApi
        zip deployment.zip Dockerrun.aws.json
        aws s3 cp deployment.zip s3://${{ env.S3_BUCKET }}

    - name: Deploy to Elastic Beanstalk
      run: |
        echo "Creating new application version "${{ github.run_id }}" for "${{ env.EB_APPLICATION }}
        aws elasticbeanstalk create-application-version --application-name ${{ env.EB_APPLICATION }} --version-label ${{ github.run_id }} --source-bundle S3Bucket=${{ env.S3_BUCKET }},S3Key="deployment.zip"
        echo "Updating beanstalk env..."
        aws elasticbeanstalk update-environment --application-name ${{ env.EB_APPLICATION }} --environment-name ${{ env.EB_ENVIRONMENT }} --version-label ${{ github.run_id }}

#    - name: Deploy to EB
#      uses: einaregilsson/beanstalk-deploy@v16
#      with:
#        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        application_name: ${{ env.CONTAINER_NAME }}
#        environment_name: ${{ env.EB_SERVICE }}
#        version_label: "simple-api-${{ github.run_id }}"
#        region: ${{ env.AWS_REGION }}
#        deployment_package: SimpleMinimalApi.zip
