name: PROD - Migrations and Deploy

on: workflow_dispatch

jobs:

  run-migrations-and-deploy-new-version:
    name: Run migrations and deploy to Dev
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update appsettings.json variables
        uses: microsoft/variable-substitution@v1
        with:
          files: 'SimpleMinimalApi/appsettings.json'
        env:
          ConnectionStrings.prodia-db: ${{ secrets.CONNECTION_STRING }}
          
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x

      - name: Install dotnet-ef tool and run migrations
        run: |
          dotnet tool install --global dotnet-ef
          dotnet build
          dotnet ef database update --project SimpleMinimalApi.DataAccess --startup-project SimpleMinimalApi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download ${{ vars.LAST_RUN_ID }} file
        run: aws s3 cp s3://${{ vars.S3_BUCKET }}/dev/${{ vars.LAST_RUN_ID }} .

      - name: Deploy to Elastic Beanstalk
        run: |
          RUN_ID=`cat ${{ vars.LAST_RUN_ID }}`
          aws elasticbeanstalk update-environment --application-name ${{ vars.EB_APPLICATION }} --environment-name ${{ vars.EB_ENVIRONMENT }} --version-label $RUN_ID