name: TEST - Build, Migrations, Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  run-migrations-and-deploy-new-version:
    name: Run migrations and deploy
    runs-on: ubuntu-latest
    environment: Test
    
    steps:
#      - name: Download repo artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: repo
#
#      - name: Set up .NET Core
#        uses: actions/setup-dotnet@v1
#        with:
#          dotnet-version: 6.x.x
#
#      - name: Install dotnet-ef tool and run migrations
#        run: |
#          dotnet tool install --global dotnet-ef
#          dotnet build
#          dotnet ef database update --project SimpleMinimalApi.DataAccess --startup-project SimpleMinimalApi
      
      - name: Run migrations
        run: echo Running migrations against TEST database...

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download ${{ vars.LAST_RUN_ID }} file
        run: aws s3 cp s3://${{ vars.S3_BUCKET }}/${{ vars.LAST_RUN_ID }} .

      - name: Deploy to Elastic Beanstalk
        run: |
          RUN_ID=`cat ${{ vars.LAST_RUN_ID }}`
          aws elasticbeanstalk update-environment --application-name ${{ vars.EB_APPLICATION }} --environment-name ${{ vars.EB_ENVIRONMENT }} --version-label $RUN_ID