name: Validation pipeline triggered on Pull Request creation
  
on:
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup .NET project
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Restore dependencies
        run: |
          cd SimpleMinimalApi
          dotnet restore
        
      - name: Build project
        run: |
          cd SimpleMinimalApi
          dotnet build --no-restore
        
      - name: Run tests
        run: |
          cd SimpleMinimalApi
          dotnet test --no-build --verbosity normal