name: Validation pipeline triggered on Pull Request creation
  
on:
  pull_request:
    branches: [ dev, main ]

jobs:
  
  test:
    runs-on: ubuntu-latest

    steps:
        
      - name: Debug variables
        run: |
          echo "Hej"
          echo ${{ vars.ECR_REPOSITORY }}
          echo ${{ vars.EB_ENVIRONMENT }}
          echo ${{ vars.EB_APPLICATION }}
          echo ${{ github.EB_APPLICATION }}
          echo ${{ vars.S3_BUCKET }}
      
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup .NET project
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build project
        run: dotnet build --no-restore
        
      - name: Run tests
        run: dotnet test --no-build --verbosity normal